javac:
	javac *.java

clean:
	find . -name "*.class" -delete
	find . -name "*.jfm" -delete
	find . -name "*.bluej" -delete
	find . -name "*.~ava" -delete
	find . -name "*.moe" -delete
	find . -name ".DS_Store" -delete

default: javac
